services:
  api1:
    build: .
    ports:
      - "8082:8082"
    environment:
      - PORT=8082

  api2:
    build: .
    ports:
      - "8083:8083"
    environment:
      - PORT=8083

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx

    depends_on:
      - api1
      - api2